# .streamlit/config.toml
[theme]
primaryColor = "#71f633"  # Hier deine Wunschfarbe als Hex-Code
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
